# Generated by Django 3.2.12 on 2023-02-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('length', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.PositiveSmallIntegerField()),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('paternallastname', models.CharField(max_length=35)),
                ('maternallastname', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('vigency', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.career')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tuitiondate', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
